name: Deploy to Lambda (Node.js)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      node-version:
        required: true
        type: string
      lambda-url:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      FUNCTION_NAME:
        required: true
      S3_BUCKET:
        required: true

jobs:
  prepare:
    name: Prepare For Deployment
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.SHA }}
    steps:

      - name: Get SHA
        id: get-sha
        run: echo "SHA=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Node dependencies
        run: |
          npm pkg delete scripts.prepare && npm ci --only=prod --omit=dev

      - name: Zip Package
        run: zip -rq lambda.zip node_modules index.js index.mjs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-zip
          path: lambda.zip
          overwrite: true

  deploy:
    name: Deploy
    needs: [ prepare ]
    uses: checkout-org/.github/.github/workflows/deploy-lambda.yml@master
    with:
      environment: ${{ inputs.environment }}
      sha: ${{ needs.prepare.outputs.sha }}
    secrets: inherit
